### ISSUE TITLE
Cannot access data that requires authentication with idToken

### ISSUE THREAD

**Issue by FvD** [Kohze/fireData#6]
I' trying to download a document using the idToken of a registerd user, but the response in the R console is "permission denied". 

```r
registered_user <- auth(api_key, email = "tests@example.com", password = "newpassword")

download(projectURL = db_url, fileName = "upstream/-L3Keo2YcFEdMFXTbqu6", 
                 token = registered_user$idToken)
```

When I try to repeat the process with cURL the message is more informative:

```
 ❯❯❯ curl -X POST -d '{"user_id" : "jack", "text" : "Ahoy!"}' \
  'https://example.firebaseio.com/upstream.json?auth=<copy pasted idToken content>'
{
  "error" : "Invalid claim 'kid' in auth header: '0uo_Iw' with iat: '1516489652'"
}
```
So after making sure to do this with a fresh token (updated iat values), I checked the idToken content on jwt.io and it contains the following:

**Header**:

```json
{
  "alg": "RS256",
  "kid": "0uo_Iw"
}
```

**Payload**:

```json
{
  "iss": "https://identitytoolkit.google.com/",
  "aud": "example",
  "iat": 1516489652,
  "exp": 1517699252,
  "user_id": "KwM0oTcpF5h4RVDGObEmJkNl1St1",
  "email": "test@example.com",
  "sign_in_provider": "password",
  "verified": false
}
```
This content seems different than the Firebase Custom Token content as [outlined here](https://firebase.google.com/docs/auth/admin/create-custom-tokens). But I am not sure if that is the correct reference I'm looking at, or even if those custom tokens are required to get token-based access to work through the http API.

It could be that my rules are not correct. I am assuming that the generic rules: 
```json
{
  "rules": {
    ".read": "auth != null",
    ".write": "auth != null"
  }
}
```
is all that is needed to require token-based access in the calls, but perhaps that is were my mistake lies. If so I would appreciate if you could give me some example rules that would work.

**Comment by Kohze** [comment]
Hallo FvD,

your comment is related to on to the issue described in #5 . We currently apparently have the problem that the generated authentication API string is not the one expected by Firebase and try currently to find a solution for that. 

> urlPath = paste0(projectURL,"/",fileName,".json?access_token=",token) 

the current programming assumes that a ```?access_token=_tokenValue_``` is the expected header. 
The firebase documentation for REST APIs says at https://firebase.google.com/docs/database/rest/auth

> curl "https://<DATABASE_NAME>.firebaseio.com/users/ada/name.json?access_token=<ACCESS_TOKEN>"

which matches the fireData function, thereby I conclude the access_token generation misses an additional "signing" step other than just taken the user token which I couldnt identify yet. 

In the meantime for dev purposes you can use the download function without the token and open the database until the problem is solved. Since time is short on my side any help is greatly appreciated to find the solution. 

>{
>  "rules": {
>    ".read": "true",
>    ".write": "true"
>  }
>}

Greetings,
Robin.

**Comment by Kohze** [comment]
fixed the issue, it was a missing ```returnSecureToken = True``` that caused the error. Now it should work as intended. I updated the repo (so a package reinstall should solve it). In case there are still issues let me know.

**Comment by Kohze** [comment]
Actually the secret key should stay secret (or be used for admins to fetch data that would otherwise not readable for users) - if it does not work without it we still have a bug. On the other hand you can always use the secretKey argument to fetch data without the token.

**Comment by Kohze** [comment]
Update: Updated the FireData package, now the code starts with a 

`if (secretKey == "none" && token == "none) {`

and therefore as result you should have the intended functionality without the secretKey argument. Thanks for finding that code error, it would certainly have costs lots of people time & nerves.
